import type { Lead } from "@/types/lead";

// Seed leads for building/previewing the UI before the FastAPI backend is wired.
// Drawn from the spec's demo data, expanded to exercise every badge state.
// The real data layer (src/lib/api.ts) will replace these.
export const MOCK_LEADS: Lead[] = [
  {
    id: "ld_1001",
    fullName: "John Doe",
    phone: "404-555-1234",
    email: "john@example.com",
    preferredContactMethod: "Phone",
    bestTimeToContact: "Afternoons",
    caseType: "Auto Accident",
    incidentDate: "2026-06-12",
    incidentLocation: "Atlanta, GA",
    incidentDescription: "Rear-ended at a traffic light.",
    injurySummary: "Neck and back pain. Went to urgent care and starting physical therapy.",
    painLevel: 6,
    medicalTreatmentReceived: true,
    treatmentDetails: "Urgent care, beginning physical therapy.",
    missedWork: true,
    lostWagesEstimate: 2400,
    hasAttorney: false,
    spokeWithInsurance: true,
    policeReportAvailable: true,
    insuranceAvailable: true,
    qualificationStatus: "Qualified",
    qualificationReason:
      "Recent rear-end accident, reported neck and back injuries, received medical treatment, not represented, police report available.",
    leadScore: 88,
    leadTemperature: "Hot",
    scoreReasoning: [
      "Caller reported neck and back injuries",
      "Caller received urgent care treatment",
      "Caller is starting physical therapy",
      "Rear-end accident suggests clearer liability",
      "Caller is not represented by another attorney",
      "Police report and photos are available",
    ],
    settlementLow: 15000,
    settlementExpected: 35000,
    settlementHigh: 75000,
    settlementConfidence: "Medium",
    pipelineStatus: "Docs Requested",
    retainerStatus: "Not Ready",
    aiSummary:
      "John Doe was involved in a rear-end auto accident on June 12, 2026 in Atlanta, GA. He reports neck and back pain, visited urgent care, and is beginning physical therapy. He is not represented and has a police report and accident photos available. The lead appears qualified and should be prioritized for attorney review.",
    missingDocuments: 2,
    lastFollowUpAt: "2026-06-18",
    createdAt: "2026-06-12T15:24:00Z",
    updatedAt: "2026-06-18T10:02:00Z",
  },
  {
    id: "ld_1002",
    fullName: "Maria Smith",
    phone: "646-555-9988",
    email: "maria@example.com",
    preferredContactMethod: "SMS",
    caseType: "Slip and Fall",
    incidentDate: "2026-05-30",
    incidentLocation: "Brooklyn, NY",
    incidentDescription: "Slipped on wet floor at grocery store.",
    injurySummary: "Wrist pain and bruising. Visited ER.",
    painLevel: 4,
    medicalTreatmentReceived: true,
    treatmentDetails: "ER visit, X-rays taken.",
    missedWork: false,
    hasAttorney: false,
    spokeWithInsurance: true,
    policeReportAvailable: false,
    insuranceAvailable: true,
    qualificationStatus: "Needs Review",
    qualificationReason:
      "ER visit for wrist injury after a fall, liability and premises notice unclear, no police report.",
    leadScore: 72,
    leadTemperature: "Warm",
    scoreReasoning: [
      "ER visit documented",
      "Premises liability requires notice evidence",
      "No police report on file",
    ],
    settlementLow: 8000,
    settlementExpected: 22000,
    settlementHigh: 50000,
    settlementConfidence: "Low",
    pipelineStatus: "Needs Review",
    retainerStatus: "Not Ready",
    aiSummary:
      "Maria Smith slipped on a wet floor at a grocery store in Brooklyn, NY on May 30, 2026. She reports wrist pain and bruising and visited the ER. Premises liability needs further review for notice and documentation.",
    missingDocuments: 3,
    lastFollowUpAt: "2026-06-15",
    createdAt: "2026-05-30T18:40:00Z",
    updatedAt: "2026-06-15T09:10:00Z",
  },
  {
    id: "ld_1003",
    fullName: "Robert Johnson",
    phone: "917-555-6789",
    email: "robert@example.com",
    preferredContactMethod: "Phone",
    caseType: "Dog Bite",
    incidentDate: "2026-06-03",
    incidentLocation: "Queens, NY",
    incidentDescription: "Bitten by neighbor's dog while walking.",
    injurySummary: "Puncture wounds on leg. Received stitches.",
    painLevel: 5,
    medicalTreatmentReceived: true,
    treatmentDetails: "Stitches, tetanus shot.",
    missedWork: true,
    lostWagesEstimate: 800,
    hasAttorney: false,
    spokeWithInsurance: false,
    policeReportAvailable: true,
    insuranceAvailable: false,
    qualificationStatus: "Qualified",
    qualificationReason:
      "Dog bite with stitches and a filed report, clear injury, not represented.",
    leadScore: 81,
    leadTemperature: "Hot",
    scoreReasoning: [
      "Puncture wounds requiring stitches",
      "Animal-control report filed",
      "Caller not represented",
    ],
    settlementLow: 10000,
    settlementExpected: 30000,
    settlementHigh: 65000,
    settlementConfidence: "Medium",
    pipelineStatus: "Qualified",
    retainerStatus: "Ready",
    aiSummary:
      "Robert Johnson was bitten by a neighbor's dog in Queens, NY on June 3, 2026, sustaining puncture wounds that required stitches. A report was filed and he is not represented. The case appears qualified and is ready for retainer review.",
    missingDocuments: 1,
    lastFollowUpAt: "2026-06-17",
    createdAt: "2026-06-03T13:05:00Z",
    updatedAt: "2026-06-17T16:45:00Z",
  },
  {
    id: "ld_1004",
    fullName: "Aisha Khan",
    phone: "212-555-3322",
    email: "aisha@example.com",
    preferredContactMethod: "Email",
    caseType: "Motorcycle Accident",
    incidentDate: "2026-06-08",
    incidentLocation: "Newark, NJ",
    incidentDescription: "Sideswiped by a car changing lanes.",
    injurySummary: "Fractured wrist and road rash. ER then orthopedic follow-up.",
    painLevel: 8,
    medicalTreatmentReceived: true,
    treatmentDetails: "ER, cast, orthopedic surgeon scheduled.",
    missedWork: true,
    lostWagesEstimate: 5200,
    hasAttorney: false,
    spokeWithInsurance: true,
    policeReportAvailable: true,
    insuranceAvailable: true,
    qualificationStatus: "Qualified",
    qualificationReason:
      "Serious injury with fracture, clear liability, police report and insurance available.",
    leadScore: 92,
    leadTemperature: "Hot",
    scoreReasoning: [
      "Fracture requiring orthopedic care",
      "Police report supports liability",
      "Insurance coverage confirmed",
      "Significant lost wages",
    ],
    settlementLow: 45000,
    settlementExpected: 95000,
    settlementHigh: 180000,
    settlementConfidence: "Medium",
    pipelineStatus: "Retainer Sent",
    retainerStatus: "Sent",
    aiSummary:
      "Aisha Khan was sideswiped on a motorcycle in Newark, NJ on June 8, 2026, suffering a fractured wrist and road rash. Treatment is ongoing with an orthopedic surgeon. Liability appears clear and a retainer has been sent.",
    missingDocuments: 0,
    lastFollowUpAt: "2026-06-19",
    createdAt: "2026-06-08T20:15:00Z",
    updatedAt: "2026-06-19T11:30:00Z",
  },
  {
    id: "ld_1005",
    fullName: "Daniel Reyes",
    phone: "305-555-7711",
    caseType: "Auto Accident",
    incidentDate: "2026-06-19",
    incidentLocation: "Miami, FL",
    incidentDescription: "Minor fender bender in a parking lot.",
    injurySummary: "No injuries reported.",
    painLevel: 0,
    medicalTreatmentReceived: false,
    missedWork: false,
    hasAttorney: false,
    spokeWithInsurance: false,
    policeReportAvailable: false,
    insuranceAvailable: true,
    qualificationStatus: "Possibly Qualified",
    qualificationReason:
      "Very recent minor collision, no injuries reported yet — follow up to confirm.",
    leadScore: 41,
    leadTemperature: "Low",
    scoreReasoning: ["No injuries reported", "Low-speed parking-lot collision"],
    settlementLow: 0,
    settlementExpected: 3000,
    settlementHigh: 8000,
    settlementConfidence: "Low",
    pipelineStatus: "Intake Complete",
    retainerStatus: "Not Ready",
    aiSummary:
      "Daniel Reyes reported a minor parking-lot fender bender in Miami, FL on June 19, 2026 with no injuries. Recommend a follow-up to confirm whether any delayed symptoms develop.",
    missingDocuments: 0,
    lastFollowUpAt: undefined,
    createdAt: "2026-06-19T09:00:00Z",
    updatedAt: "2026-06-19T09:20:00Z",
  },
  {
    id: "ld_1006",
    fullName: "Grace Liu",
    phone: "415-555-2210",
    email: "grace@example.com",
    preferredContactMethod: "Phone",
    caseType: "Truck Accident",
    incidentDate: "2026-04-22",
    incidentLocation: "Oakland, CA",
    incidentDescription: "Hit by a commercial delivery truck at an intersection.",
    injurySummary: "Herniated disc, ongoing treatment, surgery being evaluated.",
    painLevel: 9,
    medicalTreatmentReceived: true,
    treatmentDetails: "MRI, pain management, surgical consult pending.",
    missedWork: true,
    lostWagesEstimate: 14000,
    hasAttorney: false,
    spokeWithInsurance: true,
    policeReportAvailable: true,
    insuranceAvailable: true,
    qualificationStatus: "Qualified",
    qualificationReason:
      "Commercial truck collision, severe spinal injury, strong documentation and clear liability.",
    leadScore: 96,
    leadTemperature: "Hot",
    scoreReasoning: [
      "Severe spinal injury (herniated disc)",
      "Commercial defendant with insurance",
      "Police report and MRI on file",
      "Surgery under evaluation",
    ],
    settlementLow: 120000,
    settlementExpected: 240000,
    settlementHigh: 450000,
    settlementConfidence: "Medium",
    pipelineStatus: "Signed",
    retainerStatus: "Signed",
    aiSummary:
      "Grace Liu was struck by a commercial delivery truck in Oakland, CA on April 22, 2026, sustaining a herniated disc with surgery under evaluation. Documentation is strong and the client has signed a retainer.",
    missingDocuments: 0,
    lastFollowUpAt: "2026-06-16",
    createdAt: "2026-04-22T17:50:00Z",
    updatedAt: "2026-06-16T14:00:00Z",
  },
];
